config/routes.rb
Rails.application.routes.draw do
  get 'pages/panel'

root 'pages#home'
get "pages/contact"
get "pages/blog"
get "pages/faq"
get "pages/about"
get"pages/zip"

get 'sessions/new'
get 'login' => 'sessions#new'
post 'login' => 'sessions#create'
delete 'logout' => 'sessions#destroy'

  resources :users

  resources :product_attachments

  resources :products do
  resources :bids
    end

   get 'signup' => 'users#new'

  resources :subcategories
  resources :categories

end

app/views/pages/about.html.erb
<div class="col-sm-15 col-md-15">
            <div class="well">
<h1>ABOUT US </h1>
<p><h4>
<body align="center">
<br>
<br>
Back in the late 1990's, the internet was starting to become mainstream. It wasn't common for small businesses or individuals to have their own website. Very few people had the technical knowledge required to build websites and the cost was prohibitive. Having your own website was more of a novelty than anything else.
<br>

But the writing was on the wall for us and we could see the future, clear as day. Everybody was going to want their own website eventually. So learning how to build sites was a no-brainer.
<br>

Skip ahead a couple of years and that prediction was coming true. However, a few problems were becoming apparent. As a small business ourselves, there was going to be a limit on the number of websites we could directly manage and maintain for clients. The going rate for having a site made was steadily going up and pricing more businesses out of ever getting one. Something had to be done to make it easier to get a website.
<br>

Then there comes the best of best programming language Ruby and framework Rails which makes the beginner as well as the sharp end developers
to assemble the effort and make most the effort to evolve with some magnifiscent stuff.
</h4>
</p>

</body>

</div>
</div>

app/views/pages/blog.html.erb
<div class="col-sm-15 col-md-15">
            <div class="well">
            <div align ="center">
<h1>BLOG</h1>
</div>
<div align="left">
<br>
<h4>
<br>
Hey this the Developer this side saying and asking about your review which is really kind a important to us for making improvements ang the bugs and prons to get up for the best level of satisfaction.
<br>

All you need to do is to signup your Facebook account...like our facebook page that is "www.facebook.com/rails ebiz"and give comments,suggestion and whatever you want to say.it wont take long but that would really going to help us for improving the margin.
<br>

Please Use reach way of Us to You Eligibly and Sincerely....
You can also Tweet Us about your opinion on twitter.We would Glad to hear form you there.Our twitter account"www.twitter.com/rails_ebiz" and inform us with advise.
<br>

You can also subscribe and reach to us using Google+...Youtube...and Instagram for more Detailing.
<br>
</h4>



<nav class="round">
<%= image_tag("blogo.jpg", :alt => "Sample App", :class => "round",:width =>"300",:height=> "150" ) %>
</nav>

</div>

</div>
</div>

app/views/pages/contact.html.erb
<div class="col-sm-15 col-md-15">
            <div class="well">
            <div align ="center">
<h1>CONTACT US</h1>

<h4>GENERAL ENQUIRIES</h4>
<p>
help@ebizstore.com
</p>
<h4>BUSINESS RELATED ENQUIRIES</h4>
<p>
biz@ebizstore.com
</p>
<h4>OUR OPERATING HOURS</h4>
<p>
weekdays 10am to 10pm
Closed on weekends & public holidays.
</p>

<h4>HOW TO GET HERE?P</h4>
<p>
Alight at Opposite Blk 150, Kaki Bukit Avenue 1, 8 stops later.
Take a 2 minutes walk into Sham Ali Industrial Park to Blk 145.
</p>

<h4>OUR HOTLINE</h4>
<p>
(+92)3311 667453
</p>

<h4>OUR POSTAL ADDRESS</h4>
<p>
145 Block Zip Ave 1 Level 4,
Sham Ali Industrial Park,
Pakistan(416007)
</p>
<div>

</div>
</div>

app/views/pages/faq.html.erb
<div class="col-sm-15 col-md-15">
            <div class="well">
            <div align ="center">
<h1>FAQ</h1>
</div>

<h2>.How to shop here?</h2>
<p>
just sign in and the else it will be as easier as it can be just go through the buttons up at your head or use side panel.
</p>

<h2>.How will i get my product uploaded for sale?<h2>
<p>
All you need is to get some pictures of your product which need to be clear and just attach it with some required info and your are good to go.
</p>

<h2>.What's bidding?</h2>
<p>
when you want to buy product at your mutually agreed price with seller you just bid it with your name and then just sit and wait for confirmation from seller's side.
</p>

<h2>.How can i contact with other person?</h2>
<p>
All you need is to leave your email address at product's bid form and it will be seller's responsibility to get to you if and only if he is agreed to your bidded price.
</p>

<h2>.Is Signup Necessary?</h2>
<p>
Yes..
</p>

<h2>.Why to give email address?<h2>
<p>
Because you need to inform certain informations in both the cases if u being bidder or seller.
</p>


                           </div>
                           </div>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html>
<head>

  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  <style>
  .carousel-inner > .item > img,
  .carousel-inner > .item > a > img {
      width: 70%;
      margin: auto;
  }
  </style>
</head>
<body>

   <!-- <div class="navbar-header"> -->

<!--<div class="container"> -->
  <br>
  <div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
      <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
      <div class="item active">
        <img src="16.jpg" alt="girl" width="460" height="345">
      </div>

      <div class="item">
        <img src="7.jpg" alt="iphone" width="460" height="345">
      </div>

      <div class="item">
        <img src="8.jpg" alt="handbags" width="460" height="345">

      </div>

      <div class="item">
        <img src="9.jpg" alt="tv" width="460" height="345">
      </div>


       <div class="item">
        <img src="10.jpg" alt="tv" width="460" height="345">
      </div>


     <div class="item">
        <img src="zip9.jpg" alt="tv" width="460" height="345">
      </div>



    <div class="item">
        <img src="zip5.jpg" alt="tv" width="460" height="345">
      </div>


    <div class="item">
        <img src="zip10.jpg" alt="tv" width="460" height="345">
      </div>


    <div class="item">
        <img src="zip4.jpg" alt="tv" width="460" height="345">
      </div>
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>

</body>
</nav>
<div class="container">

    <div class="filler"></div>
  </div>
</div>
</style>
   <ul>
<div class="container">
    <ul class="row">
        <li link_to product_path class="col-lg-2 col-md-2 col-sm-3 col-xs-4"><img src="13.jpg"width="100" height="100"/></li>
        <li class="col-lg-2 col-md-2 col-sm-3 col-xs-4"><img src="14.jpg"width="100" height="100"/></li>
        <li class="col-lg-2 col-md-2 col-sm-3 col-xs-4"><img src="slide-6.png"width="100" height="100"/></li>
        <li class="col-lg-2 col-md-2 col-sm-3 col-xs-4"><img src="index.jpeg"width="100" height="100"/></li>
       <li class="col-lg-2 col-md-2 col-sm-3 col-xs-4"><img src="ss.jpeg"width="100" height="100"/></li>
        <li class="col-lg-2 col-md-2 col-sm-3 col-xs-4"><img src="iss.jpg"width="100" height="100"/></li>

<br><li class="col-lg-2 col-md-2 col-sm-3 col-xs-4"><img src="lpy.jpeg"width="100" height="100"/></li></b>
         <li class="col-lg-2 col-md-2 col-sm-3 col-xs-4"><img src="22.jpg"width="100" height="100"/></li>
      <li class="col-lg-2 col-md-2 col-sm-3 col-xs-4"><img src="girl2.jpg"width="100" height="100"/></li>
 <li class="col-lg-2 col-md-2 col-sm-3 col-xs-4"><img src="24.jpg"width="100" height="100"/></li>
 <li class="col-lg-2 col-md-2 col-sm-3 col-xs-4"><img src="hg.jpg"width="100" height="100"/></li>
 <li class="col-lg-2 col-md-2 col-sm-3 col-xs-4"><img src="018.jpg"width="100" height="100"/></li>

 <li class="col-lg-2 col-md-2 col-sm-3 col-xs-4"><img src="019.jpg"width="100" height="100"/></li>
 <li class="col-lg-2 col-md-2 col-sm-3 col-xs-4"><img src="oo.jpg"width="100" height="100"/></li>
 <li class="col-lg-2 col-md-2 col-sm-3 col-xs-4"><img src="zip2.jpg"width="100" height="100"/></li>
 <li class="col-lg-2 col-md-2 col-sm-3 col-xs-4"><img src="zip12.jpg"width="100" height="100"/></li>
 <li class="col-lg-2 col-md-2 col-sm-3 col-xs-4"><img src="W2.jpg"width="100" height="100"/></li>
 <li class="col-lg-2 col-md-2 col-sm-3 col-xs-4"><img src="zip8.jpg"width="100" height="100"/></li>
</ul>
</div>
   </ul>
</div>
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
 <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
      </div>
   <ul>
<br>

</body>

</footer>
<script src='//railsgirls.com/assets/bootstrap.js'></script>
</html>

app/views/pages/panel.html.erb
<div class="container">
    <div class="row">
        <div class="col-sm-3 col-md-3">
            <div class="panel-group" id="accordion">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne"><span class="glyphicon glyphicon-shopping-cart">
                            </span>Products</a>
                        </h4>
                    </div>
                    <div id="collapseOne" class="panel-collapse collapse in">
                        <div class="panel-body">
                            <table class="table">
                                <tr>
                                    <td>
                                        <span class="glyphicon glyphicon-asterisk"></span><%= link_to'Checkout Product',products_path %>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <span class="glyphicon glyphicon-pencil"></span><%= link_to 'Register Product', new_product_path %>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <span class="glyphicon glyphicon-search"></span><%=link_to 'Checkout Bids',pages_zip_path %>                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <span class="glyphicon glyphicon-picture"></span><%= link_to 'Search Through Images',product_attachments_path %>
                                    </td>
                                </tr>
                            </table>
                        </div>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo"><span class="glyphicon glyphicon-th">
                            </span>Modules</a>
                        </h4>
                    </div>
                    <div id="collapseTwo" class="panel-collapse collapse">
                        <div class="panel-body">
                            <table class="table">
                                <tr>
                                    <td>
                                        <a href="http://www.jquery2dotnet.com">Orders</a> <span class="label label-success">$ 320</span>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <a href="http://www.jquery2dotnet.com">Invoices</a>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <a href="http://www.jquery2dotnet.com">Shipments</a>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <a href="http://www.jquery2dotnet.com">Tex</a>
                                    </td>
                                </tr>
                            </table>
                        </div>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseThree"><span class="glyphicon glyphicon-user">                            </span>Account</a>
                        </h4>
                    </div>
                    <div id="collapseThree" class="panel-collapse collapse">
                        <div class="panel-body">
                            <table class="table">
                                <tr>
                                    <td>
<span class="glyphicon glyphicon-user"></span><%= link_to 'Your Products',products_path %>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
<span class="glyphicon glyphicon-user"></span><%= link_to 'Your Bid',products_path %>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
<span class="glyphicon glyphicon-user"></span><%= link_to 'Edit Profile', users_path %>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <span class="glyphicon glyphicon-trash text-danger"></span>
                                            Delete Account
                                    </td>
                                </tr>
                            </table>
                        </div>
                    </div>
                </div>

            </div>
        </div>
        <div class="col-sm-9 col-md-9">
            <div class="well">
            
<p align="center">
<p><b>Now As You Are SuccessFully LoggedIn....</b></p>
<p><b>You Have The Access To Use The Side-Panel,Use It According To Your Requirement or Need!</b></p>            

app/views/pages/zip.html.erb
<div class="container">
    <div class="row">
        <div class="col-sm-3 col-md-3">
            <div class="panel-group" id="accordion">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne"><span class="glyphicon glyphicon-shopping-cart">
                            </span>Products</a>
                        </h4>
                    </div>
                    <div id="collapseOne" class="panel-collapse collapse in">
                        <div class="panel-body">
                            <table class="table">
                                <tr>
                                    <td>
                                        <span class="glyphicon glyphicon-asterisk"></span><%= link_to'Checkout Product',products_path %>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <span class="glyphicon glyphicon-pencil"></span><%= link_to 'Register Product', new_product_path %>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <span class="glyphicon glyphicon-search"></span><%=link_to 'Checkout Bids',pages_zip_path %>                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <span class="glyphicon glyphicon-picture"></span><%= link_to 'Search Through Images',product_attachments_path %>
                                    </td>
                                </tr>
                            </table>
                        </div>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo"><span class="glyphicon glyphicon-th">
                            </span>Modules</a>
                        </h4>
                    </div>
                    <div id="collapseTwo" class="panel-collapse collapse">
                        <div class="panel-body">
                            <table class="table">
                                <tr>
                                    <td>
                                        <a href="http://www.jquery2dotnet.com">Orders</a> <span class="label label-success">$ 320</span>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <a href="http://www.jquery2dotnet.com">Invoices</a>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <a href="http://www.jquery2dotnet.com">Shipments</a>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <a href="http://www.jquery2dotnet.com">Tex</a>
                                    </td>
                                </tr>
                            </table>
                        </div>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseThree"><span class="glyphicon glyphicon-user">                            </span>Account</a>
                        </h4>
                    </div>
                    <div id="collapseThree" class="panel-collapse collapse">
                        <div class="panel-body">
                            <table class="table">
                                <tr>
                                    <td>
<span class="glyphicon glyphicon-user"></span><%= link_to 'Your Products',products_path %>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
<span class="glyphicon glyphicon-user"></span><%= link_to 'Your Bid',products_path %>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
<span class="glyphicon glyphicon-user"></span><%= link_to 'Edit Profile', users_path %>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <span class="glyphicon glyphicon-trash text-danger"></span>
                                            Delete Account
                                    </td>
                                </tr>
                            </table>
                        </div>
                    </div>
                </div>

            </div>
        </div>
        <div class="col-sm-15 col-md-15">
            <div class="well">
<h1>Search For Your Product..See its Detail And Bid !!</h1>
<p>
<%= form_tag(products_path, :method => "get", id: "search-form") do %>
<%= text_field_tag :search, params[:search], placeholder: "Search Products" %>
<b><%= submit_tag "Search" %></b>
<% end %>
</p>
<br>
</div>
</div>
</div>
</div>
<%= link_to 'Back', products_path  , :class => "btn btn-danger btn-xs"%>