config/routes.rb
Rails.application.routes.draw do
  get 'pages/panel'

root 'pages#home'
get "pages/contact"
get "pages/blog"
get "pages/faq"
get "pages/about"
get"pages/zip"

get 'sessions/new'
get 'login' => 'sessions#new'
post 'login' => 'sessions#create'
delete 'logout' => 'sessions#destroy'

  resources :users

  resources :product_attachments

  resources :products do
  resources :bids
    end

   get 'signup' => 'users#new'

  resources :subcategories
  resources :categories

end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessor :category_id
  has_many :bids
  has_many :product_attachments
  has_many :subcategories
  belongs_to :user

  accepts_nested_attributes_for :product_attachments

  validates :initial_price, numericality: true
  validates :name, presence: true, length: { maximum: 30 }
  validates :selling_price, numericality: true
  validates :description, presence: true, length: { maximum: 30 }
  validates :availibility, presence: true, length: { maximum: 30 }
  validates :subcategory_id, presence: true

  def self.search(search)
  where("name LIKE ?", "%#{search}%")
end


end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def index
 @products = Product.all
  if params[:search]
    @products = Product.search(params[:search]).order("created_at DESC")
  else
    @products = Product.all.order('created_at DESC')
  end
end

  def show
  @product_attachments = @product.product_attachments.all
  @subcategories = Subcategory.all
  end

  # GET /products/new
  def new
    @product = Product.new
    @product_attachments = @product.product_attachments.build
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
      params[:product_attachments]['avatar'].each do |a|
     @product_attachment = @product.product_attachments.create!(:avatar => a)
      end
        format.html { redirect_to products_path, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :user_id, :description, :subcategory_id, :initial_price, :selling_price, :availibility, :opening_date, :closing_date,product_attachments_attributes:[:id, :product_id,:avatar])
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<div class="container">
    <div class="row">
        <div class="col-sm-3 col-md-3">
            <div class="panel-group" id="accordion">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne"><span class="glyphicon glyphicon-shopping-cart">
                            </span>Products</a>
                        </h4>
                    </div>
                    <div id="collapseOne" class="panel-collapse collapse in">
                        <div class="panel-body">
                            <table class="table">
                                <tr>
                                    <td>
                                        <span class="glyphicon glyphicon-asterisk"></span><%= link_to'Checkout Product',products_path %>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <span class="glyphicon glyphicon-pencil"></span><%= link_to 'Register Product', new_product_path %>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <span class="glyphicon glyphicon-search"></span><%=link_to 'Checkout Bids',pages_zip_path %>                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <span class="glyphicon glyphicon-picture"></span><%= link_to 'Search Through Images',product_attachments_path %>
                                    </td>
                                </tr>
                            </table>
                        </div>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo"><span class="glyphicon glyphicon-th">
                            </span>Modules</a>
                        </h4>
                    </div>
                    <div id="collapseTwo" class="panel-collapse collapse">
                        <div class="panel-body">
                            <table class="table">
                                <tr>
                                    <td>
                                        <a href="http://www.jquery2dotnet.com">Orders</a> <span class="label label-success">$ 320</span>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <a href="http://www.jquery2dotnet.com">Invoices</a>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <a href="http://www.jquery2dotnet.com">Shipments</a>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <a href="http://www.jquery2dotnet.com">Tex</a>
                                    </td>
                                </tr>
                            </table>
                        </div>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseThree"><span class="glyphicon glyphicon-user">                            </span>Account</a>
                        </h4>
                    </div>
                    <div id="collapseThree" class="panel-collapse collapse">
                        <div class="panel-body">
                            <table class="table">
                                <tr>
                                    <td>
<span class="glyphicon glyphicon-user"></span><%= link_to 'Your Products',products_path %>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
<span class="glyphicon glyphicon-user"></span><%= link_to 'Your Bid',products_path %>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
<span class="glyphicon glyphicon-user"></span><%= link_to 'Edit Profile', users_path %>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <span class="glyphicon glyphicon-trash text-danger"></span>
                                            Delete Account
                                    </td>
                                </tr>
                            </table>
                        </div>
                    </div>
                </div>

            </div>
        </div>
        <div class="col-sm-9 col-md-9">
            <div class="well">
        <%= form_for(@product, :html => { :multipart => true }) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<%= f.fields_for :product_attachments do |p|%><%= p.label :Images%>: <%= p.file_field :avatar, :multiple => true, name: "product_attachments[avatar][]" %>
   <% end %>
       <%= f.label :name %>             :<%= f.text_field :name %>
<br>
    <%= f.label :description %>          :<%= f.text_area :description %>
<br>
    <%= f.label :category_id %>          :<%= f.collection_select(:category_id, Category.all, :id, :name) %>
<br>
     <%= f.label :subcategory %> :<%= f.grouped_collection_select(:subcategory_id, Category.order(:name), :subcategories, :name, :id, :name) %>
<br>
    <%= f.label :initial_price %> :<%= f.text_field :initial_price %>
<br>
    <%= f.label :selling_price %>: <%= f.text_field :selling_price %>
<br>
     <%= f.label :availibility%> : <%= f.label :availibility, "Yes", :value => "Availble"  %><%= f.radio_button :availibility, true %><%= f.label :availibility, "No", :value => "Sold" %><%= f.radio_button :availibility, false, :checked => true %>
<br>
    <%= f.label :opening_date %>: <%= f.text_field :opening_date ,  "data-provide" => 'datepicker' %>
<br>
    <%= f.label :closing_date %>: <%= f.text_field :closing_date ,  "data-provide" => 'datepicker' %>
<br>
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>
            </div>
        </div>
    </div>
</div>

app/views/products/edit.html.erb
<h1>Edit Regidtered Product Detail</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<div class="container">
    <div class="row">
        <div class="col-sm-3 col-md-3">
            <div class="panel-group" id="accordion">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne"><span class="glyphicon glyphicon-shopping-cart">
                            </span>Products</a>
                        </h4>
                    </div>
                    <div id="collapseOne" class="panel-collapse collapse in">
                        <div class="panel-body">
                            <table class="table">
                                <tr>
                                    <td>
                                        <span class="glyphicon glyphicon-asterisk"></span><%= link_to'Checkout Product',products_path %>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <span class="glyphicon glyphicon-pencil"></span><%= link_to 'Register Product', new_product_path %>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <span class="glyphicon glyphicon-search"></span><%=link_to 'Checkout Bids',pages_zip_path %>                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <span class="glyphicon glyphicon-picture"></span><%= link_to 'Search Through Images',product_attachments_path %>
                                    </td>
                                </tr>
                            </table>
                        </div>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo"><span class="glyphicon glyphicon-th">
                            </span>Modules</a>
                        </h4>
                    </div>
                    <div id="collapseTwo" class="panel-collapse collapse">
                        <div class="panel-body">
                            <table class="table">
                                <tr>
                                    <td>
                                        <a href="http://www.jquery2dotnet.com">Orders</a> <span class="label label-success">$ 320</span>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <a href="http://www.jquery2dotnet.com">Invoices</a>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <a href="http://www.jquery2dotnet.com">Shipments</a>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <a href="http://www.jquery2dotnet.com">Tex</a>
                                    </td>
                                </tr>
                            </table>
                        </div>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseThree"><span class="glyphicon glyphicon-user">                            </span>Account</a>
                        </h4>
                    </div>
                    <div id="collapseThree" class="panel-collapse collapse">
                        <div class="panel-body">
                            <table class="table">
                                <tr>
                                    <td>
<span class="glyphicon glyphicon-user"></span><%= link_to 'your products',products_path %>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
<span class="glyphicon glyphicon-user"></span>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
<span class="glyphicon glyphicon-user"></span><%= link_to 'Edit Profile', users_path %>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <span class="glyphicon glyphicon-trash text-danger"></span>
                                            Delete Account
                                    </td>
                                </tr>
                            </table>
                        </div>
                    </div>
                </div>

            </div>
        </div>
        <div class="col-sm-9 col-md-9">
            <div class="well">
<p id="notice"><%= notice %></p>
<table id="table1" border="3">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Availibility</th>
      <th>Selling Price</th>
      <th colspan="3"></th><
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td> <%= product.name %></td>
        <td> <%= product.description %></td>
        <td> <%= product.availibility %></td>
        <td> <%= product.selling_price %></td>

        <td><%= link_to 'Show Detail', product %> </td>
     </tr>
    <% end %>
    <p align="center">
     <%= image_tag("index9.jpeg", :alt => "Sample App", :class => "round",:width =>"600",:height=> "200", :align=>"center" ) %>
  </tbody>
</table>
<br>
<%=link_to 'Back',root_path %>
            </div>
        </div>
    </div>
</div>

app/views/products/new.html.erb
<h1>Register Your Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>
<br>

app/views/products/show.html.erb
 <div class="container">
    <div class="row">
        <div class="col-sm-3 col-md-3">
            <div class="panel-group" id="accordion">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne"><span class="glyphicon glyphicon-shopping-cart">
                            </span>Products</a>
                        </h4>
                    </div>
                    <div id="collapseOne" class="panel-collapse collapse in">
                        <div class="panel-body">
                            <table class="table">
                                <tr>
                                    <td>
                                        <span class="glyphicon glyphicon-asterisk"></span><%= link_to'Checkout Product',products_path %>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <span class="glyphicon glyphicon-pencil"></span><%= link_to 'Register Product', new_product_path %>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <span class="glyphicon glyphicon-search"></span><%=link_to 'Checkout Bids',pages_zip_path %>                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <span class="glyphicon glyphicon-picture"></span><%= link_to 'Search Through Images',product_attachments_path %>
                                    </td>
                                </tr>
                            </table>
                        </div>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo"><span class="glyphicon glyphicon-th">
                            </span>Modules</a>
                        </h4>
                    </div>
                    <div id="collapseTwo" class="panel-collapse collapse">
                        <div class="panel-body">
                            <table class="table">
                                <tr>
                                    <td>
                                        <a href="http://www.jquery2dotnet.com">Orders</a> <span class="label label-success">$ 320</span>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <a href="http://www.jquery2dotnet.com">Invoices</a>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <a href="http://www.jquery2dotnet.com">Shipments</a>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <a href="http://www.jquery2dotnet.com">Tex</a>
                                    </td>
                                </tr>
                            </table>
                        </div>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseThree"><span class="glyphicon glyphicon-user">                            </span>Account</a>
                        </h4>
                    </div>
                    <div id="collapseThree" class="panel-collapse collapse">
                        <div class="panel-body">
                            <table class="table">
                                <tr>
                                    <td>
<span class="glyphicon glyphicon-user"></span><%= link_to 'Your Products',products_path %>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
<span class="glyphicon glyphicon-user"></span><%= link_to 'Your Bid',products_path %>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
<span class="glyphicon glyphicon-user"></span><%= link_to 'Edit Profile', users_path %>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <span class="glyphicon glyphicon-trash text-danger"></span>
                                            Delete Account
                                    </td>
                                </tr>
                            </table>
                        </div>
                    </div>
                </div>

            </div>
        </div>
        <div class="col-sm-9 col-md-9">
            <div class="well">
            <id="notice"><%= notice %></p>
<div class="image-container1">
<% @product_attachments.each do |p| %>
  <%= image_tag (p.avatar_url  (:thumb).to_s) %>
<% end %>
</div>
<span style="text-decoration: underline;" "align: center;">"<strong><%= @product.name %>"</span></strong>

  <br>
  <table id="table1" border="3">
 <strong>Description:-</strong><%= @product.description %>
  <br>

  <strong>Subcategory:-</strong>  <%= @product.subcategory_id %>
  <br>

  <strong>Initial price:-</strong> $<%= @product.initial_price %>
  <br>

  <strong>Selling price:-</strong> $<%= @product.selling_price %>
<br>
<span style="text-decoration: underline;" "align: center;><strong> Running price:-</span></strong> $<% @bprice = Bid.group('product_id').maximum(:bidding_price)[@product.id] %><% if @bprice %><%= @bprice %><% else %><%= @product.initial_price %><% end %>
  <br>

<strong>Availibility:-</strong>   <%= @product.availibility %>
  <br>

  <strong>Opening date:-</strong>  <%= @product.opening_date %>
  <br>

<strong>Closing date:-</strong>  <%= @product.closing_date %>
  <br>

<p>
<h2><b> <%= link_to "Bids", "#", id: "bids-link" %></b></h2>
</p>
   <section id="bids-section">
    <ol id="bids">
     <%= render @product.bids %>
    </ol>
  <p>
  <%= image_tag("hh.jpeg", :alt => "Sample App", :class => "round",:width =>"250",:height=> "200", :align=>"right" ) %>
<h2> <strong>Start Bidding !!</strong></h2>
<%= form_for([@product, @product.bids.build], remote: true) do |f| %>
<b> One Warning: Seller Can't Bids Its Own Product </b>
  <p>
    <%= f.label :bidding_price %><br>
    <%= f.text_field :bidding_price %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>
</section>
</p>

<%= link_to 'Edit', edit_product_path(@product) , :class => "btn btn-info btn-xs" %> |

<%= link_to 'Back', products_path  , :class => "btn btn-danger btn-xs"%>
<br>
</div>
</div>