config/routes.rb
Rails.application.routes.draw do
  get 'pages/panel'

root 'pages#home'
get "pages/contact"
get "pages/blog"
get "pages/faq"
get "pages/about"
get"pages/zip"

get 'sessions/new'
get 'login' => 'sessions#new'
post 'login' => 'sessions#create'
delete 'logout' => 'sessions#destroy'

  resources :users

  resources :product_attachments

  resources :products do
  resources :bids
    end

   get 'signup' => 'users#new'

  resources :subcategories
  resources :categories

end

app/views/layouts/_footer.html.erb
<footer class="navbar navbar-fixed-bottom ">
                  <p align="center">
                             Rails Ebiz Apps © 2015

</p>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-custom">
  <div class="navbar-inner">
    <div class="container">
     <nav>

<nav class=" navbar-right">
<span class="glyphicon glyphicon-user">
<% if logged_in? %>Hi <%= current_user.name %><br>
<%= link_to "LogOut",logout_path,method: "delete", :class => "btn btn-danger btn-xs" %><br>
<%= link_to "Recovery",pages_panel_path, :class => "btn btn-danger btn-xs" %>
<% else %>
<%= link_to "LogIn",login_path, :class => "btn btn-danger btn-xs" %>
<% end %>
</span>
</nav>

        <%= link_to("Home", root_path, class: "btn btn-default") %>
        <%= link_to("Blog", pages_blog_path, class: "btn btn-info") %>
        <%= link_to("About Us", pages_about_path, class: "btn btn-primary") %>
        <%= link_to("Contact",pages_contact_path, class: "btn btn-warning") %>
        <%= link_to("FAQ", pages_faq_path, class: "btn btn-danger") %>
</nav>
</div>
</div> 

<IMG STYLE="position:absolute; TOP:0px; center:2px; WIDTH:80px; HEIGHT:60px" SRC="logo.png">

</header>

app/views/layouts/_stylesheets.html.erb
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print', :media => 'print' %>
<%= stylesheet_link_tag 'custom', :media => 'screen'%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FYPPP</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render'layouts/stylesheets'%>
</head>
<body>
<div class="container">
<%= render'layouts/header'%>
    <section class ="round">
 <%= yield %>
</section>
<% flash.each do |message_type,message| %>
<%= message %>
<% end %>
<%= render'layouts/footer' %>
</body>
</html>

app/views/layouts/top.html.erb
<div id="wrapper">
<div class="container">
<%= render'layouts/header'%>
<div class="container">
    <div class="row">
        <div class="col-sm-3 col-md-3">
            <div class="panel-group" id="accordion">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                   <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
                   <span class="glyphicon glyphicon-folder-close">
                            </span>Products</a>
                        </h4>
                    </div>
                    <div id="collapse no-open-lmao" class="panel-collapse collapse in">
                        <div class="panel-body">
                            <table class="table">
                                <tr>
                                    <td>
                                        <span class="glyphicon glyphicon-pencil text-primary"></span>
                               <%= link_to 'Product', products_path %>
                                        </td>
                                </tr>
                                <tr>
                                    <td>
                                        <span class="glyphicon glyphicon-flash text-success"></span><%= link_to 'Register product', new_product_path %>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <span class="glyphicon glyphicon-file text-info"></span><%= link_to 'Checkout Bids' , pages_zip_path   %>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <span class="glyphicon glyphicon-comment text-success"></span><%=link_to 'Find Through Images',product_attachments_path %>
                                    </td>
                                </tr>
                            </table>
                        </div>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a data-toggle="collapse " data-parent="#accordion" href="#collapseTwo"><span class="glyphicon glyphicon-th">
                            </span>Modules</a>
                        </h4>
                    </div>
                    <div id="collapseTwo" class="panel-collapse collapse">
                        <div class="panel-body">
                            <table class="table">
                                <tr>
                                    <td>
                                        <a>Prices</a><span>$</span>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <a>Invoices</a>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <a>Delivery</a>
                                </tr>
                                <tr>
                                    <td>
                                        <a>Tax</a>
                                    </td>
                                </tr>
                            </table>
                        </div>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseThree"><span class="glyphicon glyphicon-user">
                            </span>Account</a>
                        </h4>
                    </div>
                    <div id="collapseThree" class="panel-collapse collapse">
                        <div class="panel-body">
                            <table class="table">
                                <tr>
                                    <td>

                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <a>Notifications</a> <span class="label label-info">?</span>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <a>Import/Export</a>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <span class="glyphicon glyphicon-trash text-danger"></span><a href="class="text-danger">
                                            Delete Account</a>
                                    </td>
                                </tr>
                            </table>
                        </div>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseFour"><span class="glyphicon glyphicon-file">
                            </span>Reports</a>
                        </h4>
                    </div>
                    <div id="collapseFour" class="panel-collapse collapse">
                        <div class="panel-body">
                            <table class="table">
                                <tr>
                                    <td>
                                        <span class="glyphicon glyphicon-usd"></span><a>Sales</a>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <span class="glyphicon glyphicon-user"></span><a>Customers</a>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <span class="glyphicon glyphicon-tasks"></span><a>Products</a>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <span class="glyphicon glyphicon-shopping-cart"></span><a>Shopping Cart</a>
                                    </td>
                                </tr>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-9 col-md-9">